# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trivial Fis
email: ybbs.daans@hotmail.com
description: Computer science
author: trivialfis
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trivialfis.github.io" # the base hostname & protocol for your site
twitter_username: ""
github_username:  trivialfis
google_analytics: UA-104056626-1
paginate: 10

plugins:
    - jekyll-feed
    - kramdown
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-paginate

# Build settings
markdown: kramdown
